services:
  api:
    container_name: opscore-api-prod
    build:
      context: /opt/pitaya/opscore/api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.production
    expose:
      - "3005"
    networks:
      - pitaya_net

networks:
  pitaya_net:
    external: true
